# Supabase credentials
supabase_url = "https://nwmnfplwvxvkelcqaiay.supabase.co"
supabase_key = "sb_secret_No71cZiZAt_XFSW9XBneoA_8xiChYWC"

# Email (SMTP)
smtp_server = "smtp.gmail.com"
smtp_port = "587"
smtp_user = "braxsimmons01@gmail.com"
smtp_pass = "spsg vewt cbic anpi"