supabase_url = "https://nwmnfplwvxvkelcqaiay.supabase.co"
supabase_service_key = "sb_secret_No71cZiZAt_XFSW9XBneoA_8xiChYWC"

smtp_server = "smtp.gmail.com"
smtp_port = "587"
smtp_user = "braxdon.simmons@triplebaviation.com"
smtp_pass = "Hauula2019!"  # Gmail App Password or mail relay
